# Generated by Django 5.2.8 on 2025-11-23 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='qc.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('style', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('po_number', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('Proto', 'Proto'), ('PPS', 'PPS'), ('Production', 'Production')], default='PPS', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('front', 'front'), ('defect', 'defect')], max_length=10)),
                ('image', models.ImageField(upload_to='inspection_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qc.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pom_name', models.CharField(max_length=255)),
                ('tol', models.FloatField(default=0.0)),
                ('std', models.FloatField(default=0.0)),
                ('s1', models.FloatField(blank=True, null=True)),
                ('s2', models.FloatField(blank=True, null=True)),
                ('s3', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAIL', 'FAIL')], default='OK', max_length=10)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='qc.inspection')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qc.template'),
        ),
        migrations.CreateModel(
            name='TemplatePOM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_tol', models.FloatField(default=0.0)),
                ('default_std', models.FloatField(default=0.0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poms', to='qc.template')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
