# Generated by Django 5.2.8 on 2025-11-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionimage',
            name='type',
        ),
        migrations.AddField(
            model_name='inspectionimage',
            name='caption',
            field=models.CharField(default='Inspection Image', max_length=100),
        ),
    ]
