# Generated by Django 5.2.8 on 2025-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0002_remove_inspectionimage_type_inspectionimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='customer_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qa_accessories_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qa_fabric_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qa_fit_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qa_wash_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qa_workmanship_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='s4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='s5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='s6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='decision',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Represent', 'Represent')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='stage',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Proto', 'Proto'), ('Fit', 'Fit'), ('SMS', 'SMS'), ('Size Set', 'Size Set'), ('Production', 'Production')], default='Proto', max_length=20),
        ),
    ]
