# Generated by Django 5.2.8 on 2025-11-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0003_inspection_customer_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='customer_remarks',
            field=models.TextField(blank=True, verbose_name='Customer Feedback'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_accessories_comments',
            field=models.TextField(blank=True, verbose_name='Accessories Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_fabric_comments',
            field=models.TextField(blank=True, verbose_name='Fabric Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_fit_comments',
            field=models.TextField(blank=True, verbose_name='Fit Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_wash_comments',
            field=models.TextField(blank=True, verbose_name='Wash Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_workmanship_comments',
            field=models.TextField(blank=True, verbose_name='Workmanship Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='General Remarks'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templatepom',
            name='default_std',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
