# Generated by Django 5.2.8 on 2025-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0004_alter_inspection_customer_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeremail',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customeremail',
            name='email_type',
            field=models.CharField(choices=[('to', 'To'), ('cc', 'CC')], default='to', max_length=2),
        ),
    ]
