# Generated by Django 5.2.8 on 2025-11-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0005_customeremail_contact_name_customeremail_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='stage',
            field=models.CharField(choices=[('Dev', 'Dev'), ('Proto', 'Proto'), ('Fit', 'Fit'), ('SMS', 'SMS'), ('Size Set', 'Size Set'), ('PPS', 'PPS')], default='Proto', max_length=20),
        ),
    ]
