# Generated by Django 5.2.8 on 2025-11-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0007_alter_inspection_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='qc.customer'),
        ),
    ]
