# Generated by Django 5.2.8 on 2025-12-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0009_filterpreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='customer_decision',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Revision Requested', 'Revision Requested'), ('Accepted with Comments', 'Accepted with Comments'), ('Held Internally', 'Held Internally')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_feedback_comments',
            field=models.TextField(blank=True, verbose_name='Customer Feedback Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_feedback_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
