# Generated by Django 5.2.8 on 2025-12-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0010_inspection_customer_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='customer_feedback_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
