# Generated by Django 5.2.8 on 2025-12-02 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0011_alter_inspection_customer_feedback_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('factory', models.CharField(blank=True, max_length=255)),
                ('inspection_date', models.DateField()),
                ('order_no', models.CharField(max_length=255)),
                ('style_no', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('total_order_qty', models.PositiveIntegerField(default=0)),
                ('presented_qty', models.PositiveIntegerField(default=0)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('aql_critical', models.FloatField(default=0.0)),
                ('aql_major', models.FloatField(default=2.5)),
                ('aql_minor', models.FloatField(default=4.0)),
                ('critical_found', models.PositiveIntegerField(default=0)),
                ('major_found', models.PositiveIntegerField(default=0)),
                ('minor_found', models.PositiveIntegerField(default=0)),
                ('max_allowed_critical', models.PositiveIntegerField(default=0)),
                ('max_allowed_major', models.PositiveIntegerField(default=0)),
                ('max_allowed_minor', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Pending', max_length=20)),
                ('total_cartons', models.PositiveIntegerField(default=0)),
                ('selected_cartons', models.PositiveIntegerField(default=0)),
                ('carton_length', models.FloatField(default=0.0, help_text='Length in cm')),
                ('carton_width', models.FloatField(default=0.0, help_text='Width in cm')),
                ('carton_height', models.FloatField(default=0.0, help_text='Height in cm')),
                ('gross_weight', models.FloatField(default=0.0, help_text='Gross weight in kg')),
                ('net_weight', models.FloatField(default=0.0, help_text='Net weight in kg')),
                ('quantity_check', models.BooleanField(default=False)),
                ('workmanship', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('packing_method', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('marking_label', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('data_measurement', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('hand_feel', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('NA', 'N/A')], default='NA', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_inspections', to='qc.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalInspectionDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], default='Minor', max_length=10)),
                ('count', models.PositiveIntegerField(default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='final_inspection_defects/')),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='qc.finalinspection')),
            ],
            options={
                'ordering': ['severity', 'description'],
            },
        ),
        migrations.CreateModel(
            name='FinalInspectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='final_inspection_images/')),
                ('caption', models.CharField(default='Final Inspection Image', max_length=255)),
                ('category', models.CharField(choices=[('Packaging', 'Packaging'), ('Defect', 'Defect'), ('General', 'General'), ('Measurement', 'Measurement')], default='General', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qc.finalinspection')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalInspectionSizeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50)),
                ('order_qty', models.PositiveIntegerField(default=0)),
                ('packed_qty', models.PositiveIntegerField(default=0)),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_checks', to='qc.finalinspection')),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
