# Generated by Django 5.2.9 on 2025-12-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0012_finalinspection_finalinspectiondefect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinspection',
            name='aql_standard',
            field=models.CharField(choices=[('strict', 'Strict (0/1.5/2.5)'), ('standard', 'Standard (0/2.5/4.0)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='finalinspectionimage',
            name='category',
            field=models.CharField(choices=[('Packaging', 'Packaging'), ('Labeling', 'Labeling'), ('Defect', 'Defect'), ('General', 'General'), ('Measurement', 'Measurement'), ('On-Site Test', 'On-Site Test')], default='General', max_length=20),
        ),
    ]
