# Generated by Django 5.2.9 on 2025-12-02 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0013_finalinspection_aql_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalInspectionMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pom', models.CharField(max_length=255)),
                ('tolerance', models.FloatField(default=0.0)),
                ('standard', models.FloatField(default=0.0)),
                ('s1', models.CharField(blank=True, max_length=50)),
                ('s2', models.CharField(blank=True, max_length=50)),
                ('s3', models.CharField(blank=True, max_length=50)),
                ('s4', models.CharField(blank=True, max_length=50)),
                ('s5', models.CharField(blank=True, max_length=50)),
                ('final_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='qc.finalinspection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
