# Generated by Django 5.2.9 on 2025-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0014_finalinspectionmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinspectionmeasurement',
            name='s6',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
