# Generated by Django 5.2.9 on 2025-12-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0015_finalinspectionmeasurement_s6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalinspectionmeasurement',
            old_name='pom',
            new_name='pom_name',
        ),
        migrations.RenameField(
            model_name='finalinspectionmeasurement',
            old_name='standard',
            new_name='spec',
        ),
        migrations.RenameField(
            model_name='finalinspectionmeasurement',
            old_name='tolerance',
            new_name='tol',
        ),
    ]
