# Generated by Django 5.2.9 on 2025-12-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0016_rename_pom_finalinspectionmeasurement_pom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinspectionmeasurement',
            name='size_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
