# Generated by Django 5.2.8 on 2025-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0017_finalinspectionmeasurement_size_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalinspection',
            name='inspection_attempt',
            field=models.CharField(choices=[('1st', '1st Inspection'), ('2nd', '2nd Inspection (Re-inspection)'), ('3rd', '3rd Inspection (Final Re-inspection)')], default='1st', help_text='Inspection attempt number for this order', max_length=20),
        ),
    ]
