# Generated by Django 5.2.8 on 2025-12-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc', '0018_finalinspection_inspection_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='accessories_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_accessories_comments',
            field=models.TextField(blank=True, verbose_name='Customer Accessories Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_comments_addressed',
            field=models.BooleanField(default=False, help_text='Check if all customer points are resolved'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_fabric_comments',
            field=models.TextField(blank=True, verbose_name='Customer Fabric Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_fit_comments',
            field=models.TextField(blank=True, verbose_name='Customer Fit Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_wash_comments',
            field=models.TextField(blank=True, verbose_name='Customer Wash Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='customer_workmanship_comments',
            field=models.TextField(blank=True, verbose_name='Customer Workmanship Comments'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fabric_handfeel',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('Not OK', 'Not OK')], default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='inspection',
            name='fabric_pilling',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('High', 'High')], default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='inspection_attempt',
            field=models.CharField(choices=[('1st', '1st Inspection'), ('2nd', '2nd Inspection'), ('3rd', '3rd Inspection')], default='1st', help_text='Inspection attempt number for this order', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='customer_remarks',
            field=models.TextField(blank=True, verbose_name='Customer Feedback Summary'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_accessories_comments',
            field=models.TextField(blank=True, verbose_name='QA Accessories Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_fabric_comments',
            field=models.TextField(blank=True, verbose_name='QA Fabric Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_fit_comments',
            field=models.TextField(blank=True, verbose_name='QA Fit Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_wash_comments',
            field=models.TextField(blank=True, verbose_name='QA Wash Comments'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qa_workmanship_comments',
            field=models.TextField(blank=True, verbose_name='QA Workmanship Comments'),
        ),
    ]
